# 服务设置
server:
  port: 8080 # 端口

# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&allowMultiQueries=true
    hikari:
      maximum-pool-size: 9
      keepalive-time: 30000
# xxl job 定时配置
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8090/xxl-job-admin
    executor:
      appname: xxl-job-executor-sample
      ip: 127.0.0.1
      port: 9999

# Mybatis配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml # Mapper XML 扫包路径
  type-aliases-package: com.x.demo.entity # 类别名映射
  configuration:
    map-underscore-to-camel-case: true # 驼峰映射